experimentName: 4mC_C.equisetifolia
experimentWorkingDirectory: /mnt/8t/jjr/iDNA-ABF-automl/nni-experiments/4mC_C.equisetifolia
trialCommand: python3 pl_nni_train_fusion.py
trialCodeDirectory: .
trialGpuNumber: 1
#machineList:
#  useActiveGpu: true
#  maxTrialNumPerGpu: 4
trialConcurrency: 4
maxTrialNumber: 1000
maxTrialDuration: 2h
maxExperimentDuration: 60h
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: true
  gpuIndices: 0,1,2,3
  maxTrialNumberPerGpu: 2
search_space_file: ./search_space_fusion.json