add_special_tokens: False
#checkpoint: '../log/test_CKPT.ckpt'
checkpoint: null
command: script-test
k_fold: 5
log_dir: '/mnt/sdb/home/jjr/iDNA-ABF-automl/log/'
max_length: 41
onehot: False
model: 'ClassificationDNAbert'
model_hparams: 'ClassificationDNAbert.yaml'
auto_ml: false
nni_metric: 'F1'
output_dir: null
padding: 'max_length'
path_visual_data: null
project_name: bert
proportion: null
path_pretrain_model: null # '../Rostlab_prot_t5_xl_uniref50'
gpus: 1

path_train_data: '../data/DNA_MS/tsv/4mC/4mC_S.cerevisiae/train.tsv'
path_valid_data: '../data/DNA_MS/tsv/4mC/4mC_S.cerevisiae/test.tsv'
path_test_data: '../data/DNA_MS/tsv/4mC/4mC_S.cerevisiae/test.tsv'

return_tensors: 'pt'
seed: 9999
train_mode: 'train'

threshold: 0.95
kmer: 6